#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 001-i-want-to-improve-the-new-matcher

set -e

echo "========================================"
echo "NBA Matcher Fix - Development Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT_ROOT="/Users/solen/GitHub/Playbook"

# ============================================
# VERIFY ENVIRONMENT
# ============================================

echo ""
echo "Checking Python environment..."

cd "$PROJECT_ROOT"

# Check if venv exists
if [ -d ".venv" ]; then
    echo -e "${GREEN}Virtual environment found${NC}"
    source .venv/bin/activate
else
    echo -e "${YELLOW}Creating virtual environment...${NC}"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -e .
    pip install -r requirements-dev.txt
fi

# Verify pytest is available
if command -v pytest &> /dev/null; then
    echo -e "${GREEN}pytest available${NC}"
else
    echo -e "${YELLOW}Installing dev dependencies...${NC}"
    pip install -r requirements-dev.txt
fi

# ============================================
# VERIFY TESTS PASS (baseline)
# ============================================

echo ""
echo "Running baseline tests..."

if pytest tests/ -q --tb=no; then
    echo -e "${GREEN}All baseline tests pass${NC}"
else
    echo -e "${RED}WARNING: Some baseline tests are failing${NC}"
    echo "This may affect the implementation"
fi

# ============================================
# VERIFY KEY FILES EXIST
# ============================================

echo ""
echo "Verifying key files exist..."

FILES_TO_CHECK=(
    "src/playbook/team_aliases.py"
    "src/playbook/matcher.py"
    "src/playbook/parsers/structured_filename.py"
    "tests/test_matcher.py"
    "tests/test_structured_matcher.py"
)

for file in "${FILES_TO_CHECK[@]}"; do
    if [ -f "$PROJECT_ROOT/$file" ]; then
        echo -e "${GREEN}✓ $file${NC}"
    else
        echo -e "${RED}✗ $file (MISSING)${NC}"
    fi
done

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Project: $PROJECT_ROOT"
echo "Python:  $(python --version)"
echo "Pytest:  $(pytest --version | head -1)"
echo ""
echo "Key commands:"
echo "  pytest tests/test_matcher.py tests/test_structured_matcher.py -v"
echo "  pytest tests/ -v"
echo ""
echo "Files to modify:"
echo "  - src/playbook/team_aliases.py (add NBA aliases)"
echo "  - src/playbook/matcher.py (fix scoring logic)"
echo "  - src/playbook/parsers/structured_filename.py (verify date parsing)"
echo "  - tests/test_matcher.py (add NBA tests)"
echo "  - tests/test_structured_matcher.py (add NBA tests)"
echo ""
